### ISSUE TITLE
LPPD E2E testing

### ISSUE THREAD

**Issue by pgoos** [Sifchain/sifchain-ui#720]
Basic Test case:

- given new account add 10k rowan to any given pool
- given new account owns 10% of share in the pool
- given LPD policy is set to distribute 5% over 100 blocks
- when 100 blocks pass
- then LP should have received 5% of 10% of pool native balance in rowan in its wallet

Specific cases:
- [ ] Case #1 (LP added before reaching distribution_period_start_block)
- [ ] Case #2 LP added after distribution_period_start_block  and before distribution_period_end_block
- [ ] Case #3 LP added before after distribution_period_start_block and re-added before distribution_period_end_block
- [ ] Case #4 LP added before reaching distribution_period_start_block and partially removed before distribution_period_end_block
- [ ] Case #5 LP added before reaching distribution_period_start_block and fully removed before distribution_period_end_block

**Comment by pandaring2you** [comment]
Was blocked on broken testnet. Chainops says they fixed testnet. Piotr to validate. We do not need tempnet to finish regression testing.

**Comment by pandaring2you** [comment]
Aiming to complete by tomorrow

**Comment by pandaring2you** [comment]
finished

**Comment by pandaring2you** [comment]
finished
